### ISSUE TITLE
Doesnt work on Windows 8.1 x64

### ISSUE THREAD

**Issue by foi** [koct9i/ioping#24]
Time always equal 0, outside hard I\O doesn't affect on time. But tmp file is creating.
![default](https://cloud.githubusercontent.com/assets/26715/9214875/723c898c-40cd-11e5-969f-31d121129d97.PNG)

**Comment by koct9i** [comment]
As you see ioping warns about unreliable results: use writes (add -W, that's safe for directories).
Seems like windows have no non-cached reads, at least I haven't found any.

**Comment by acataluddi** [comment]
HI @koct9i,  

Unfortunately I'm getting the same results also by using the suggested `-W` parameter:

![immagine](https://user-images.githubusercontent.com/8874358/86452213-41dda480-bd1c-11ea-83ed-1fa840d0c90a.png)

Do you have any suggestion to measure latency on Windows?

Thanks,  
Adriano C.

**Comment by koct9i** [comment]
Probably clock precision is too rough. Try bigger requests.
