### ISSUE TITLE
GCC doesn't inline now()

### ISSUE THREAD

**Issue by sriemer** [koct9i/ioping#28]
I've tested latest code from Git HEAD on Debian Wheezy with the gcc 4.7 compiler and noticed that the now() function isn't inlined although it is very small.

From `objdump -S` output on x86_64:
````
        time_now = now();
  40161e:       e8 4d 12 00 00          callq  402870 <now>
````

Making `now()` "static inline" results in 10 us less latency in average.

**Comment by koct9i** [comment]
I don't see such huge difference on my hardware (ordianry x86 laptop)
Anyway I've made it static inline and switched to clock_gettime() which gives nanosecond precision.
