### ISSUE TITLE
Differences in values between block device and mount point

### ISSUE THREAD

**Issue by Yotouille** [koct9i/ioping#31]
Hi,

There's no problem here, only want to ask a question about the huge difference I observe when iopinging a mount point vs his equivalent block device. I've searched a bit about it but cannot find a clue, could someone explain what is happening ?

On mount point (`sudo ioping -c4 /`)
```
--- / (ext4 /dev/dm-0) ioping statistics ---
4 requests completed in 3.00 s, 2.08 k iops, 8.15 MiB/s
min/avg/max/mdev = 288 us / 479 us / 752 us / 169 us
```

On block device (`sudo ioping -c4 /dev/dm-0`)
```
--- /dev/dm-0 (block device 5.51 GiB) ioping statistics ---
4 requests completed in 3.05 s, 75 iops, 302.0 KiB/s
min/avg/max/mdev = 7.72 ms / 13.2 ms / 20.1 ms / 4.77 ms
```

Thanks for your help !

**Comment by koct9i** [comment]
For testing directory ioping creates 1mb temporary file (see option -S) it fits into hdd cache. For device it use whole range.

**Comment by Yotouille** [comment]
Ok ! Thanks a lot !
