### ISSUE TITLE
is ioping destructive in any way?

### ISSUE THREAD

**Issue by ckozler** [koct9i/ioping#33]
This is likely a stupid question but I have incorrectly used tools like this before which I did not know were writing to the block device (it wasnt evident from the man pages)

That said, if I simply do

ioping .

What does this do exactly? How does it measure if it doesnt actually write a file (I couldnt see it writing anything)

All I see in strace is a call to fadvise64, pread64, and then write() to write to the console

**Comment by koct9i** [comment]
By default it non-destructive: without option "-W" ioping measures reads.

"-W" has simple protection: without repeating it three times ioping wouldn't write anything into existing file or block device.

> ioping .
creates temporary file (O_TMPFILE or unlinked), writes random data (-S <bytes>) and starts measurement.

**Comment by ckozler** [comment]
Thanks for the clarification and confirmation
