### ISSUE TITLE
possible contribution - wrapper script for nagios/cron

### ISSUE THREAD

**Issue by ckozler** [koct9i/ioping#34]
Hi there!

I just discovered this tool today and its been immensely useful. I wanted to let you know I wrote this script which can integrate with nagios or as a standalone script in cron or something

Perhaps you can link to it if you want, but in either case figured maybe you or someone else here would find it useful https://github.com/ckozler/iomonitor 

Thank you for creating such a tool. Its been something I've been looking for for a very long time

**Comment by koct9i** [comment]
Ok. BTW it has batch mode just for that:

$ ioping -c 3 -B .
3 2991 1003 4108325 215 997 2541 1092

see raw statistics format in manpage

**Comment by ckozler** [comment]
Right, I misread that my first time around in the man page. I could use that and then not have to parse each column. I can make an update to it to use -B and pipe to awk to get the 3 fields I care about. Thanks
