### ISSUE TITLE
latency histogram

### ISSUE THREAD

**Issue by navytux** [koct9i/ioping#35]
Hello up there.

First of all I'd like to say thanks for the useful ioping tool - we use it as part of benchmarking SSDs underlying our database setup, but not only that.

Sometimes it gives more information to know not only min/avg/max statistics about disk latency, but also latency distribution, and I've made a patch to do so:

https://lab.nexedi.com/kirr/ioping/commit/000c0931
https://lab.nexedi.com/kirr/ioping/commit/34c97f76

The patch is however quick and dirty and imho not yet ready to be merged upstream (at least I think so).
However it works for us and with this issue I wanted upstream and people around to at least know there is a draft implementation.

Here is e.g. how it looks like as part of whole benchmark run:

https://lab.nexedi.com/kirr/neo/blob/29170dee/go/time-soct17-z6001-z600.txt

( I've made a small shell wrapper around ioping which also amends its output with unified golang benchmarking format:

https://lab.nexedi.com/kirr/neo/blob/29170dee/go/neo/t/neotest#L825
https://github.com/golang/proposal/blob/master/design/14313-benchmark-format.md

That's why there are also `Benchmark...` lines emitted. )

Unfortunately I won't probably have time in the near future to work on cleaning the patch, so please don't expect me to rework it in non-minor ways if that would be required. I appologize for that beforehand.

Thanks again for ioping,
Kirill

**Comment by koct9i** [comment]
There is standard and much more powerful tool for that: fio
https://git.kernel.org/pub/scm/linux/kernel/git/axboe/fio.git/

I don't see reason to compete with it.

**Comment by navytux** [comment]
ok
