### ISSUE TITLE
overflow warning when building with gcc 9.2

### ISSUE THREAD

**Issue by HRio** [koct9i/ioping#43]
I get a overflow warning when building ioping with gcc 9.2.0 on Linux

```
gcc -o ioping ioping.c -Os -fomit-frame-pointer -std=gnu99 -Wall -Wextra -pedantic -Wl,--as-needed -lm -lrt
ioping.c: In function 'get_device_size':                           
ioping.c:828:18: warning: overflow in conversion from 'long unsigned int' to 'int' changes value from '2148012658' to '-2146954638' [-Woverflow]
  828 |  ret = ioctl(fd, BLKGETSIZE64, &blksize);                             
      |                  ^~~~~~~~~~~~       
```

**Comment by HRio** [comment]
Note building ioping version 1.2

**Comment by koct9i** [comment]
Which distributive is it?

Second argument in ioctl() should be unsigned long:

$ grep -w ioctl /usr/include/x86_64-linux-gnu/sys/ioctl.h
...
extern int ioctl (int __fd, unsigned long int __request, ...) __THROW;

**Comment by HRio** [comment]
Alpine Linux (hence musl libc).

```
$ grep -w ioctl /usr/include/sys/ioctl.h
#include <bits/ioctl.h>
int ioctl (int, int, ...);
```
POSIX specification https://pubs.opengroup.org/onlinepubs/009604599/functions/ioctl.html

I guess `unsigned long` as second arg to ioctl() is in fact `__GLIBC__` specific?

**Comment by koct9i** [comment]
In Linux it's unsigned long. That's bug in musl.
