### ISSUE TITLE
No destination specified issue on windows

### ISSUE THREAD

**Issue by aamodvelangi** [koct9i/ioping#44]
I am trying to use Ioping on windows and am using the following command:
ioping -c 100 PD1 (PD1 is my drive)... but I keep getting an error saying ' No destination specified'.
P.S. I am using latest version

**Comment by koct9i** [comment]
Under PD1 you mean \\\\.\PhysicalDrive1 ?
Not sure this windows magic will work, never tested it.

ioping expects where path to directory where it creates temporary file.
