### ISSUE TITLE
Build fails with glibc 2.39

### ISSUE THREAD

**Issue by bbonev** [koct9i/ioping#50]
Error message:

```` c
In file included from /xxx/x86_64-pc-linux-gnu/x86_64-pc-linux-gnu/sysroot/usr/include/linux/fs.h:19,
                 from /xxx/x86_64-pc-linux-gnu/x86_64-pc-linux-gnu/sysroot/usr/include/linux/aio_abi.h:31,
                 from ioping.c:891:
/xxx/x86_64-pc-linux-gnu/x86_64-pc-linux-gnu/sysroot/usr/include/linux/mount.h:95:6: error: redeclaration of 'enum fsconfig_command'
   95 | enum fsconfig_command {
      |      ^~~~~~~~~~~~~~~~
````
As per my understanding, `linux/aio_abi.h` pulls `linux/fs.h` which in turn conflicts with `sys/mount.h`. `glibc` does not expose the API from `linux/aio_abi.h` and as a quick and dirty fix replacing `sys/mount.h` with `linux/fs.h` does the trick.

But I am not sure if that is a proper way to fix it, that is why an issue instead of PR.

**Comment by koct9i** [comment]
This seems will be fixed in next glibc https://sourceware.org/git/?p=glibc.git;a=commit;h=774058d72942249f71d74e7f2b639f77184160a6

linux/fs.h must be included first time after undef RWF_NOWAIT to define it back and preserve magic which detects aio header without aio_rw_flags.

**Comment by bbonev** [comment]
Good catch. I couldn't find that fix, seems like the proper one to rely on...
Also fixed the version is the issue title
