### ISSUE TITLE
Consider new release for glibc-2.36 (and other fixes)

### ISSUE THREAD

**Issue by thesamesam** [koct9i/ioping#51]
Hi!

The fix for https://github.com/koct9i/ioping/issues/50 (https://github.com/koct9i/ioping/commit/d771a202788e8e097f6449743b33a9cf3af54d24) doesn't apply cleanly to the last release and there's a bunch of other worthwhile looking fixes in master.

Would it be possible to have a new release so distributions can pick up the fixes more easily?

Thanks!

**Comment by koct9i** [comment]
done

**Comment by thesamesam** [comment]
Thanks!
